# version: 2 not supported by goreleaser 1.26.2
# Using implicit version 1

before:
  hooks:
    - go mod tidy
    - go mod download

builds:
  # CLI binary (all platforms)
  - id: cli
    main: ./cmd/time-tracker-bot
    binary: time-tracker-bot
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w -X main.version={{.Version}}

archives:
  # Main archives (CLI binary only)
  - id: default
    builds:
      - cli
    format: tar.gz
    name_template: >-
      {{ .ProjectName }}_
      {{- .Version }}_
      {{- .Os }}_
      {{- .Arch }}
    format_overrides:
      - goos: windows
        format: zip
    files:
      - README.md
      - config.example.yaml

checksum:
  name_template: 'checksums.txt'

snapshot:
  name_template: "{{ incpatch .Version }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^chore:'
      - '^ci:'

release:
  github:
    owner: zappbrannigan34
    name: Yandex-Tracker-Time-Manager-Bot
  draft: false
  prerelease: auto
